USE [master]
GO

/****** Object:  Database [MEDICAL]    Script Date: 09/03/2018 11:09:39 ******/
CREATE DATABASE [MEDICAL] ON  PRIMARY 
( NAME = N'MEDICAL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\MEDICAL.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MEDICAL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\MEDICAL_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MEDICAL] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MEDICAL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MEDICAL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MEDICAL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MEDICAL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MEDICAL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MEDICAL] SET ARITHABORT OFF 
GO

ALTER DATABASE [MEDICAL] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MEDICAL] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MEDICAL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MEDICAL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MEDICAL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MEDICAL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MEDICAL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MEDICAL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MEDICAL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MEDICAL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MEDICAL] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MEDICAL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MEDICAL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MEDICAL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MEDICAL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MEDICAL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MEDICAL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MEDICAL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MEDICAL] SET  READ_WRITE 
GO

ALTER DATABASE [MEDICAL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MEDICAL] SET  MULTI_USER 
GO

ALTER DATABASE [MEDICAL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MEDICAL] SET DB_CHAINING OFF 
GO

